### ISSUE TITLE
if-clause is always true

### ISSUE THREAD

**Issue by rob313663** [atmel-maxtouch/mxt-app#55]
File:
mxt-app/src/mxt-app/bootloader.c

Variable:
unsigned char bootloader_id;

Expression:
if (bootloader_id | 0x20) { ... } else { ... }

The if-clause will always evaluate to true. Looks strange.

/rob

**Comment by ndyer** [comment]
It's a straight bug, it's meant to be testing the bit so it should be " & ".

For reference, this is the same code in the device driver: https://github.com/ndyer/linux/blob/for-upstream/drivers/input/touchscreen/atmel_mxt_ts.c#L652
