### ISSUE TITLE
Test command often times out

### ISSUE THREAD

**Issue by mfuzzey** [atmel-maxtouch/mxt-app#6]
In v1.18 the test command (mxt-app --test=01) often (but not always times out)
This is when using the sysfs v1 interface.

The reason is that the test command calls, mxt_msg_reset()
Which does,
int sysfs_msg_reset(struct mxt_device *mxt)
{
  int ret;

  mxt->sysfs.mtimestamp = 0;
  ret = get_uptime(&mxt->sysfs.timestamp);

  return ret;
}

get_uptime() is implemented using the sysinfo() system call which always rounds up to the next second.

This value is then used to filter out any dmesg entries before this time.
The result is that , unless the comand is issued close enough to the end of the second for the log message generated by the kernel as the test reponse to be in the next second the message is lost and the command times out.

Example with some logs added:
root@PC12445-BES:~# mxt-app -v 2 --test=01
Version:1.18
Registered sysfs path:/sys/bus/i2c/drivers/atmel_mxt_ts/0-004a
Enabling self test object

Disabling noise suppression
TOUCH_MULTITOUCHSCREEN_T9[0] enabled
  UPSIGLIM:30000
  LOSIGLIM:20000
TOUCH_KEYARRAY_T15[0] disabled
  UPSIGLIM:0
  LOSIGLIM:0
Running Analog power test
@MF@ found 0 new messages total=344 matched=341 new=0 mxt=0 first=0.0 last=3560.793171 ts=3561.0
@MF@ found 0 new messages total=344 matched=341 new=0 mxt=0 first=0.0 last=3560.793171 ts=3560.793171
...
Timeout

ts above is the value of mxt->sysfs.timestamp in sysfs_get_msg_count()
it was set to 3561 by sysfs_msg_reset() hence the reply is ignored...

dmesg shows that the response WAS received  3560.791631
root@PC12445-BES:~# dmesg | tail
[ 3560.791631] atmel_mxt_ts 0-004a: MXT MSG: 0e fe 00 00 00 00 00 00
[ 3560.793171] atmel_mxt_ts 0-004a: MXT MSG: ff fe 00 00 00 00 00 00

**Comment by ndyer** [comment]
Believed fixed by 56b0554864f3af005
