### ISSUE TITLE
AOSP build still broken

### ISSUE THREAD

**Issue by gibsson** [atmel-maxtouch/mxt-app#60]
Hi,

By cherry-picking my patch you apparently didn't move the Android.mk to the top folder.

However, not having it in the top folder breaks the build with the following issue:
build/core/base_rules.mk:183: *** external/mxt-app/lib/libusbdroid/code/src/LibUSBDroid/jni: MODULE.TARGET.STATIC_LIBRARIES.libusbdroid already defined by external/mxt-app/jni/../lib/libusbdroid/code/src/LibUSBDroid/jni.

The reason is that Android parses all the folder while searching for Android.mk. As soon as it hits one, it depends on that Android.mk to point to sub folders.

In your case, the jni/Android.mk includes all the other Android.mk (not in sub folders) and then the Android build system still parses the other folder, hence see twice the same Android.mk.

So it either needs to be put at top level or removed completely.

Regards,
Gary

**Comment by mgong98** [comment]
Closing bug.  Did not see any compile issues when using NDK r11 or NDK r17.  Please resubmit bug report with duplication steps if still needed.
