### ISSUE TITLE
AOSP build still broken

### ISSUE THREAD

**Issue by bneuen** [atmel-maxtouch/mxt-app#66]
Top-level Android.mk is in the wrong place (see issue #60), so build (NDK r12b) breaks with:

including ./external/mp4parser/Android.mk ...
including ./external/mtpd/Android.mk ...
including ./external/mxt-app/jni/Android.mk ...
including ./external/mxt-app/lib/libusbdroid/Android.mk ...
build/core/base_rules.mk:157: *** external/mxt-app/lib/libusbdroid/code/src/LibUSBDroid/jni: MODULE.TARGET.STATIC_LIBRARIES.libusbdroid already defined by external/mxt-app/jni/../lib/libusbdroid/code/src/LibUSBDroid/jni.  Stop.

**Comment by bneuen** [comment]
See pull request Fix AOSP build #67

**Comment by bneuen** [comment]
This should be fixed as of 5f6821917fa948a535299324c6c58129be910a9e

**Comment by atmeltouchlab** [comment]
Closing bug.  Code verified.
