### ISSUE TITLE
I2C error when all tests, broken line, sensor variant invoked through script

### ISSUE THREAD

**Issue by ninadwalvekar2019** [atmel-maxtouch/mxt-app#77]
I am calling all test, broken line , sensor variant test back to back in a script and this results in an i2c error. Attached script test_nodelay prints the error on the console. The error occurs after the first test. The second one fails
However if I put a delay as in the test.sh script everything works fine.

Details of the setup:- 
mxt-app version mxt-app 1.28-19-g4e9daa7
kernel version :- 4.14

Attached is a log file of the error:- mxt-app-error

Note that the commands are tried by adding a reset command after every test still the same behavior.

**Comment by atmeltouchlab** [comment]
Can you reattach the log files and the script you are using.  They don't seem to be in the bug.

**Comment by ninadwalvekar2019** [comment]
[logs.zip](https://github.com/atmel-maxtouch/mxt-app/files/3818793/logs.zip)

**Comment by atmeltouchlab** [comment]
A delay has been added after the reset of device.  Modification added to https://github.com/atmel-maxtouch/mxt-app/commit/550d39855dc8df888df70183e272624e7d238a87.

**Comment by atmeltouchlab** [comment]
Closing issue.
